### ISSUE TITLE
Error in example (content instead of value)

### ISSUE THREAD

**Issue by PascalAnimateur** [stefanpenner/async-disk-cache#15]
There's an error in the example code given in README.md ... the property holding the cache entry's content is named `value`, not `content`.

Thus the example should look like this:
```
cache.get('foo').then(function(cacheEntry) {
  cacheEntry === {
    isCached: true,
    path: 'foo',
    value: 'content of foo'
  }
});
```

**Comment by Turbo87** [comment]
@PascalAnimateur could you open a PR for that?

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/async-disk-cache/commit/e814cbf9f46f82757fb6d7037b6d6ff60c5265a6
