### ISSUE TITLE
Add environment variable to override usage of `os.tmpDir()`.

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/async-disk-cache#2]
This would allow us to utilize a known path as the cache location, and then we can utilize Travis caching to take advantage of warm boots in CI also.

I would like https://github.com/stefanpenner/async-disk-cache/blob/master/index.js#L81 to become:

```javascript
this.tmpDir = options.location || process.env['ASYNC_DISK_CACHE_ROOT'] || tmpDir;
```

Then we could use a path that is in the CI services (both Travis and Circle support these options) cached directory listing, and get much faster CI builds...

**Comment by rwjblue** [comment]
I'm happy to implement, but wanted to confirm on direction first.

**Comment by stefanpenner** [comment]
Isn't the root already configurable? If so the env var should be handled by the consuming lib.

If not I would prefer to just make it configurable, and keep the flag downstream.

**Comment by rwjblue** [comment]
@stefanpenner - Yes, the root is configurable. I could have the same effect by adding these changes to broccoli-persistent-filter if that is your preference (where it lives doesn't matter too much to me, I just want the functionality).

**Comment by rwjblue** [comment]
Closing this and opening a new one in broccoli-persistent-filter.

**Comment by stefanpenner** [comment]
@rwjblue yup it is. Awesome thanks
