### ISSUE TITLE
Infinite loop on windows when key includes invalid characters for filesystem

### ISSUE THREAD

**Issue by JoelWAnna** [stefanpenner/async-disk-cache#21]
root cause of https://github.com/kimroen/ember-cli-coffeescript/issues/112
broccoli-coffee uses the characters `"`, `:` in the key, which when ultimately called in writeP
infinitely recurses as reason.code is ENOENT

https://github.com/stefanpenner/async-disk-cache/blob/master/index.js#L173

you should be able to reproduce (on windows) with

```
AsyncDiskCache = require('async-disk-cache')
cache = new AsyncDiskCache
cache.set('foo/:/1', 'bar')
```

hmm, not sure this is really an issue for this project.
it seems the infinite loop is within mkdirp, there is a pending PR from a couple years ago on mkdirp that fixes this https://github.com/substack/node-mkdirp/pull/74/commits

**Comment by stefanpenner** [comment]
What are valid char allowed for DIR in windows?

**Comment by JoelWAnna** [comment]
this is the what is reported as invalid by the .net api https://msdn.microsoft.com/en-us/library/system.io.path.getinvalidfilenamechars(v=vs.110).aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-2

although `:` is not included in the list, but is not valid for a path either.
```
The following characters are invalid in a path:
Char    Hex Value
",      0022
<,      003C
>,      003E
|,      007C
 ,      0000
☺,      0001
☻,      0002
♥,      0003
♦,      0004
♣,      0005
♠,      0006
,       0007
,       0008
,       0009
,       000A
,       000B
,       000C
,       000D
♫,      000E
☼,      000F
►,      0010
◄,      0011
↕,      0012
‼,      0013
¶,      0014
§,      0015
▬,      0016
↨,      0017
↑,      0018
↓,      0019
→,      001A
←,      001B
∟,      001C
↔,      001D
▲,      001E
▼,      001F

The following characters are invalid in a filename:
Char    Hex Value
",      0022
<,      003C
>,      003E
|,      007C
 ,      0000
☺,      0001
☻,      0002
♥,      0003
♦,      0004
♣,      0005
♠,      0006
,       0007
,       0008
,       0009
,       000A
,       000B
,       000C
,       000D
♫,      000E
☼,      000F
►,      0010
◄,      0011
↕,      0012
‼,      0013
¶,      0014
§,      0015
▬,      0016
↨,      0017
↑,      0018
↓,      0019
→,      001A
←,      001B
∟,      001C
↔,      001D
▲,      001E
▼,      001F
:,      003A
*,      002A
?,      003F
\,      005C
/,      002F
```

**Comment by stefanpenner** [comment]
thanks, it seems like we could encode those here and be good to go.

**Comment by stefanpenner** [comment]
sorry for letting this linger: https://github.com/stefanpenner/async-disk-cache/pull/42 should address
