### ISSUE TITLE
istextorbinary dependency not compatible with Node 0.10

### ISSUE THREAD

**Issue by Turbo87** [stefanpenner/async-disk-cache#27]
see https://github.com/bevry/istextorbinary/blob/master/package.json#L58

this is relevant due to:
```
└─┬ ember-cli-htmlbars@1.1.0
  └─┬ broccoli-persistent-filter@1.2.11
    └─┬ async-disk-cache@1.0.8
      └── istextorbinary@2.1.0
```

/cc @stefanpenner @nathanhammond

**Comment by stefanpenner** [comment]
@Turbo87 ya, it is also an opt-in feature. So we should be ok? https://github.com/stefanpenner/async-disk-cache/blob/master/index.js#L32-L33

**Comment by Turbo87** [comment]
ah okay.  I was warned by NPM when installing my app with node 0.10 about an incompatible engine, that's why I wanted to point this out.
