### ISSUE TITLE
Use a consistent base path to allow easier clearing of cache folders.

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/async-disk-cache#3]
To allow easier clearing of the cache, I would like to store all caches for `async-disk-cache` in a subdirectory of `this.tmpDir` instead of its root.  This would not add significant cost to the build times, but it would allow us to know what directories in `tmpDir` are from async-disk-cache.

Specifically, I would suggest the following change [here](https://github.com/stefanpenner/async-disk-cache/blob/master/index.js#L84):

```javascript
this.root = path.join(this.tmpDir, 'async-disk-cache', this.key);
```

**Comment by stefanpenner** [comment]
:+1:

**Comment by john-kurkowski** [comment]
Done in 2244990513a7a417ecbf5e0845db0a144a682aca?

**Comment by rwjblue** [comment]
Thanks @john-kurkowski, I completely forgot to close this!
