### ISSUE TITLE
Fails when invalid character used.

### ISSUE THREAD

**Issue by ibnuda** [stefanpenner/async-disk-cache#30]
Maybe it's not the right place to report this bug, but actually I do have to delete the "if-you-need-to-delete-this-open-an-issue-async-disk-cache" directory.

Disclaimer, I don't know what the author have done with their code, but as far as I know, the usage of invalid character in Windows system always fails.

![something related to async disk cache](https://cloud.githubusercontent.com/assets/8169908/20381055/3d278422-acd8-11e6-8313-77457ca7bbbe.PNG)

**Comment by stefanpenner** [comment]
@ibnuda interesting, thanks for reporting

**Comment by stefanpenner** [comment]
i believe the issue is [here](https://github.com/ivanvotti/broccoli-svg-optimizer) Which version of broccoli-svg-optimizer do you have ?

**Comment by ibnuda** [comment]
It look like the application uses broccoli-svg-optimizer version "^1.0.1"

**Comment by stefanpenner** [comment]
@ibnuda i suspect your issue is with that project. My recommendation is to open an issue there

**Comment by ibnuda** [comment]
Okay. Thanks for the time.
