### ISSUE TITLE
building via docker cache isn't cleaned up

### ISSUE THREAD

**Issue by meirish** [stefanpenner/async-disk-cache#31]
I've got a `if-you-need-to-delete-this-open-an-issue-async-disk-cache` folder in the root of my ember-cli application - what do you need to troubleshoot?

**Comment by stefanpenner** [comment]
interesting, where is you TMPDIR?

**Comment by meirish** [comment]
We're running it like this: 
`docker run --rm -v "$(pwd)":/working/dir -w /working/dir image` - the `CMD` block in the docker file then runs a make target that does all of the ember app installation and then builds it - the ember app is located at `/working/dir/ui`.

It looks like `$TMPDIR` is blank, though when I try to`export` it in the `CMD` block to something like `/working/dir/ui/tmp` I still end up with the delete-me folder in the `ui` dir.

**Comment by meirish** [comment]
I can try to work up a bare-bones repro repo later today or tomorrow.

**Comment by stefanpenner** [comment]
> It looks like $TMPDIR is blank, though when I try toexport it in the CMD block to something like /working/dir/ui/tmp I still end up with the delete-me folder in the ui dir.

sounds suspicious. 

> I can try to work up a bare-bones repro repo later today or tomorrow.

this would be lovely.

**Comment by stefanpenner** [comment]
related: https://github.com/stefanpenner/async-disk-cache/issues/35

**Comment by hugomaiavieira** [comment]
When running on docker with `root` user, you can add this instruction into your Dockerfile to fix the problem:

``` Dockerfile
RUN npm config set unsafe-perm true
```

You can check [this npm issue comments](https://github.com/npm/npm/issues/4531) for more info.

**Comment by stefanpenner** [comment]
@hugomaiavieira I'm not i fully understand that fix, could you submit a more complete TL;DR. Once i understand when/how/what/why I can totally add it.

I would normally try to reproduce myself in docker, I am just fairly pressed for time currently.

**Comment by hugomaiavieira** [comment]
@stefanpenner I'm afraid I can't write a TL;DR about it. I'm not too familiar with Node and its environment. Anyway, I will try to summarize my findings.

I've taken a look at [os.tmpdir](https://github.com/nodejs/node/blob/bdc09c63e6ee9208ebab7e77ac513705263bbd9a/lib/os.js#L124) code and [some](https://github.com/nodejs/node/blob/master/src/node_credentials.cc#L72) of its [dependencies](https://github.com/nodejs/node/blob/master/src/node_credentials.cc#L37). Still, I also couldn't fully understand why it ignores the env vars and creates the cache folder in the root of my ember-cli application when setting `TMPDIR=/tmp` on `Dockerfile` or `docker-compose.yml` and running docker container as `root` user.

Besides the reference I've mentioned earlier, I've also found other ones that had the same problem, and they have used the `--unsafe-perm` as a solution. [This](https://codepen.io/Merri/post/notes-on-npm-running-inside-a-docker-container) for example:

> ... file permissions and how files are generated is an issue. At first I tackled issues with cache files by using `--unsafe-perm` option with `npm`, because `os.tmpdir()` returns current working directory and not `/tmp` when running `npm` as `root` user.

But the same [post](https://codepen.io/Merri/post/notes-on-npm-running-inside-a-docker-container) mentions another way (and probably a better one) to solve the problem. Setting the `TMPDIR` in the `package.json`, like this:

```json
{
  "scripts": {
    "ember": "TMPDIR=/tmp ember"
  }
}
```

This way, when running `npm run ember -- serve`, the cache files will be created in the `/tmp` folder correctly the same way as the other `--unsafe-perm` solution.

I believe I couldn't answer your "w" questions, but I hope I could help :slightly_smiling_face:
