### ISSUE TITLE
Using up inode limit

### ISSUE THREAD

**Issue by SaladFork** [stefanpenner/async-disk-cache#32]
We are building a medium-sized Ember application in a CI environment running Jenkins on an AWS EC2 instance. We are finding that `/tmp/if-you-need-to-delete-this-open-an-issue-async-disk-cache` never gets cleaned out and continues to grow until we run out of inodes. Clearing it today brought our inode usage on the machine down from 95% to 30%. This is causing all our other builds to fail as Jenkins is no longer able to create new files.

**Comment by stefanpenner** [comment]
@SaladFork interesting, many OS's clean this out periodically. Usually based on last access.

If yours does not, maybe periodic cleaning is required?

**Comment by SaladFork** [comment]
Yep, we're setting up a cron job to clean it out automatically. Given the folder name we thought it best to file an issue too.

**Comment by stefanpenner** [comment]
@SaladFork yup, good call opening this issue.  As maybe we can do something better here.

My understanding, was that most `linux` did something similar to OSX. For example Ubuntu i believe uses [tmpreaper](http://manpages.ubuntu.com/manpages/wily/man8/tmpreaper.8.html) for this task.

**Comment by SaladFork** [comment]
We are using Ubuntu 14.04.4 LTS; odd that tmpreaper (or such) isn't cleaning up here...

**Comment by stefanpenner** [comment]
@SaladFork  askubuntu claims Ubuntu 14.04 uses tmpreaper, which is invoked from `etc/cron.daily` http://askubuntu.com/a/759048

Prior to 14.04 http://askubuntu.com/a/20831 claims `/etc/init/mounted-tmp.conf` which runs each time `tmp` is mounted, which in practice is typically on restart.

Obviously the restart variant is not desirable. I believe success lies in figuring out whats-up with `tmpreaper` being missing..

**Comment by SaraaraS** [comment]
Ran into the same issue. Jenkins on aws ec2 medium instance running Ubuntu 14.04.4 LTS, inodes got eaten up, logging in and installing tmpreaper and adding it to the daily cron fixed the issue.
