### ISSUE TITLE
Using all the inodes

### ISSUE THREAD

**Issue by MiLk** [stefanpenner/async-disk-cache#35]
This is a follow up of #32 which was closed without a real solution.

We had the same issue with a jenkins job building an ember application.
The cache folder was not in `/tmp`, because each job should only write into its workspace.

So broccoli-persistent-filter and async-disk-cache keep putting files without ever cleaning them.
It's not the task of the OS to clean up files left by a software running on it.

Can we expect a solution which is not letting the OS clean the garbage left?

**Comment by rwjblue** [comment]
> Can we expect a solution which is not letting the OS clean the garbage left?

Absolutely! Just delete the persistent cache directory as part of your CI jobs cleanup.  

> It's not the task of the OS to clean up files left by a software running on it.

I respectfully disagree. 😺

---

You can customize the base path for the persistent storage via an environment variable. At that point you could config it to be somewhere in the workspace and clean it up after each job.

**Comment by stefanpenner** [comment]
Having an OS which does not purge TMP_DIR will lead to other issues. Alternatively, we could allow users to disable the cache entirely...

**Comment by rwjblue** [comment]
IMO, we should allow it to be disabled completely (unrelated to this issue though). For example, it would make testing cold builds much easier...

**Comment by stefanpenner** [comment]
> For example, it would make testing cold builds much easier...

Yup.

```
DISABLE_DISK_CACHE=true
```

So that both SYNC and ASYNC DISK_CACHE's abide

**Comment by stefanpenner** [comment]
Left a note in the readme: https://github.com/stefanpenner/async-disk-cache/blob/master/README.md#helpmy-tmp-dir-is-growing-unbounded

If that is not sufficient, please help me understand why and I will gladly expand on it.
