### ISSUE TITLE
Remove extra `mkdirp` calls.

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/async-disk-cache#4]
We are currently calling `mkdirp` for every cache set operation to ensure that the containing directory is created before writing the file ([here](https://github.com/stefanpenner/async-disk-cache/blob/65566bf107c734a10f6afeaba0cb3a2231b646a4/index.js#L151)).  Unfortunately, this results in a ton of extra file system calls (`mkdirp` recursively calls `fs.exists` for each segment in the provided path even if the path exists).

We should instead, attempt to write to the path and if an error (generally `ENOENT`) occurs then call `mkdirp`.

**Comment by stefanpenner** [comment]
Optimistically assuming the dir exists should work well for the typically workload here
