### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by keithws** [stefanpenner/async-disk-cache#47]
Sometimes, async-disk-cache generates filenames that are longer than 255 characters. This causes HFS+ (on macOS) to throw the ENAMETOOLONG error.

After reviewing the code, it looks the the file name is just the key in Base64, so obviously long keys will produce long filenames.

Also, Base64 seems problematic since it may include "/" characters which will be parsed as a directory separator.

This problem is typically solved by producing a hash of the key and storing it in hex, or less common, Base62.

**Comment by stefanpenner** [comment]
thanks for the issue report, and the fix. I also ported your fix to https://github.com/stefanpenner/sync-disk-cache
