### ISSUE TITLE
if-you-need-to-delete-this-open-an-issue-async-disk-cache size keeps growing

### ISSUE THREAD

**Issue by tigressbailey** [stefanpenner/async-disk-cache#62]
We are using Jenkins to build our Ember application.
A temporary GUID name file keeps growing its size and eat up all the inodes in our server in `/tmp/if-you-need-to-delete-this-open-an-issue-async-disk-cache` folder.

Can you please help to resolve this issue?  Thanks!

Additionally, what if I delete this folder? Do any bad things gonna happen during the CI? 
Or do we have an elegant solution for it?

**Comment by TigressBailey** [comment]
Hi @rwjblue @stefanpenner 
Are you available to help with this?

**Comment by stefanpenner** [comment]
Sorry about the late reply, I have added a section to the readme: https://github.com/stefanpenner/async-disk-cache/blob/master/README.md#helpmy-tmp-dir-is-growing-unbounded

If that does not help, please feel free to share why not, and I will gladly expand.
