### ISSUE TITLE
Had to delete "if-you-need-to-delete-this-open-an-issue-async-disk-cache"

### ISSUE THREAD

**Issue by cab** [stefanpenner/async-disk-cache#63]
Issue was related to https://github.com/stefanpenner/broccoli-persistent-filter.

Kept getting `unexpected end of file` build errors. Setting `BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT` to a local directory fixed it, and then deleting the `if-you-need...` directory and NOT setting `BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT` also fixed it.

**Comment by stefanpenner** [comment]
I am pretty sure the following PR https://github.com/stefanpenner/async-disk-cache/pull/67 will address.
