### ISSUE TITLE
Race condition when sharing cache

### ISSUE THREAD

**Issue by ef4** [stefanpenner/async-disk-cache#66]
If the persistent cache is being accessed by more than one process, it's possible to see partially-written records in the cache.

Instead we could write each new file to a globally unique temporary name and then atomically rename it to the real shared name.

Same issue on the sync sibling of this library: https://github.com/stefanpenner/sync-disk-cache/issues/18

**Comment by ef4** [comment]
@stefanpenner I think this issue causes sporadic failures in embroider's test suite, since we build multiple ember apps in parallel.

**Comment by stefanpenner** [comment]
@ef4 yes, the original design took this into account and opted for less IO's and 1 build of the current app. The issue has come up several times though, maybe we need to incur the cost of the extra IO and write elsewhere, and move in atomically.

**Comment by stefanpenner** [comment]
I suppose one could implement a sort of locking, where if a "someone else is actively using this cache" is present, we fall back into the slower atomic write then move. 

That may be a reasonable balance.

**Comment by ef4** [comment]
I think the problem with the locking idea is that you really need to check for the lock *every time*. So it may be just as expensive as always using the slower path.

As long as we put the temporary file in the same directory as the permanent file, I would expect the rename to be quite cheap. The added IO isn't proportional to file size, it's the constant cost of updating the directory's inode table. I guess if the directories are very big that could be the issue -- reducing the branching factor of the cache through nesting may help with that.

**Comment by stefanpenner** [comment]
@ef4 ya, good idea. Local rename sounds like a good path forward.

**Comment by simon-o-matic** [comment]
I should have looked at the issues list before I started! I have a single process using the cache, but it appears to be getting corrupted files every now and then under pressure. So must be this same race condition.
