### ISSUE TITLE
Temporary files are created with access rights that are too permissive 

### ISSUE THREAD

**Issue by mgraham** [stefanpenner/async-disk-cache#71]
It seems like temp directories are created with mode 0775 (group-writable) and files are created with mode 0666 (group-writable and world-writable).  This was brought to our attention during a security audit.

Is there any reason this cannot be made more restrictive?  On the face of it, it seems like a security risk to allow other users and processes to make changes to your temporary files.
Temporary files should really just be writeable by the current user (mode 0700 for directories and mode 0600 for files).  

Or the code could just to respect the user's umask - that would probably be best.

**Comment by rwjblue** [comment]
Seems reasonable to me.

@stefanpenner - What do you think?

**Comment by stefanpenner** [comment]
Given that we use the username as part of the `tmpdir` this seems like a change that shouldn't have any negative consequences. I'm would gladly accept a PR which makes that change to both this repo and https://github.com/stefanpenner/sync-disk-cache

**Comment by stefanpenner** [comment]
Thinking about it further, I think that the executable bit shouldn't be set in this case. I suspect that `664` is more appropriate.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/async-disk-cache/pull/72

**Comment by mgraham** [comment]
I'm sorry that I missed reviewing this.  Thank you!
